### ISSUE TITLE
Pipe in Chain style

### ISSUE THREAD

**Issue by kongdd** [oxinabox/Pipe.jl#22]
Any idea how to implement Pipe in Chain style?

```julia
@chain df begin
  dropmissing
  filter(:id => >(6), _)
  groupby(:group)
  combine(:age => sum)
end
# Expected:
@pipe df |>
  dropmissing |>
  filter(:id => >(6), _)|>
  groupby(:group) |>
  combine(:age => sum)
```

**Comment by oxinabox** [comment]
Pipe.jl, by design, does not feature any implict locations.
It is intentionally explict.

There are many similar packages with similar features but slightly different
https://github.com/JuliaLang/julia/issues/5571#issuecomment-205754539

In particular, as I recall Hose.jl is a fork of Pipe.jl with the implict _ first argument, which you want
https://github.com/FNj/Hose.jl/
